### ISSUE TITLE
Quick start guide & mouse clicks request

### ISSUE THREAD

**Issue by Rigidoont** [sammwyy/OSKD#1]
This is amazing! A huge thank you for creating this! I do have a small suggestion: it would be incredibly helpful to include a brief guide on how to get started. It took me a bit to figure everything out.

For anyone looking for a quick start, here's a simple step-by-step:

1. Download `oskd-windows-x64.exe` file from the latest release on Releases page here: [https://github.com/sammwyy/OSKD/releases](https://github.com/sammwyy/OSKD/releases).
2. Once downloaded, go ahead and run the .exe file.
3. Open OBS and add a new "Browser" source.
4. In the "URL" field, type in "[http://127.0.0.1:41770](http://127.0.0.1:41770/)". If you don't see the "URL" field, uncheck the "Local file" checkbox.
5. Save the source, adjust its position to your preference.

Also, I'd love to see a feature that visually represents mouse clicks - like displaying "Right-click" when you right-click, and so on for other mouse buttons like the left and middle clicks.

Despite the project seeming inactive with no updates in nearly a year, I'm holding out hope for its future development. This is truly a fantastic addition to OBS!

**Comment by sammwyy** [comment]
It sounds good, I really didn't use this project again because I didn't program in stream again and that's why I didn't give it much importance, but I'll update it soon.

**Comment by sammwyy** [comment]
Added to get started to README ^^
